const cyrillicToLatinUppercase: Record<string, string> = {
    'А': 'A', 
    'Ә': 'Á', 
    'Б': 'B', 
    'В': 'V',
    'Г': 'G',
    'Ғ': 'Ǵ',
    'Д': 'D',
    'Е': 'E',
    'Ё': 'Yo',
    'Ж': 'J',
    'З': 'Z',
    'И': 'I',
    'Й': 'Y',
    'К': 'K',
    'Қ': 'Q', 
    'Л': 'L',
    'М': 'M',
    'Н': 'N',
    'Ң': 'Ń', 
    'О': 'O',
    'Ө': 'Ó',
    'П': 'P',
    'Р': 'R',
    'С': 'S',
    'Т': 'T',
    'У': 'U',
    'Ү': 'Ú',
    'Ў': 'W',
    'Ф': 'F',
    'Х': 'X',
    'Ҳ': 'H',
    'Ц': 'C',
    'Ч': 'Ch',
    'Ш': 'Sh',
    'Щ': 'Sh',
    'Ъ': '', 
    'Ы': 'Í',
    'Ь': '', 
    'Э': 'E', 
    'Ю': 'Yu',
    'Я': 'Ya'
  };
  
  const cyrillicToLatinLowercase: Record<string, string> = {
    'а': 'a',
    'ә': 'á',
    'б': 'b',
    'в': 'v',
    'г': 'g',
    'ғ': 'ǵ',
    'д': 'd',
    'е': 'e',
    'ё': 'yo', 
    'ж': 'j', 
    'з': 'z',
    'и': 'i',
    'й': 'y',
    'к': 'k',
    'қ': 'q',
    'л': 'l',
    'м': 'm',
    'н': 'n',
    'ң': 'ń',
    'о': 'o',
    'ө': 'ó',
    'п': 'p',
    'р': 'r',
    'с': 's',
    'т': 't',
    'у': 'u',
    'ү': 'ú',
    'ў': 'w',
    'ф': 'f',
    'х': 'x',
    'ҳ': 'h',
    'ц': 'c',
    'ч': 'ch',
    'ш': 'sh',
    'щ': 'sh',
    'ъ': '',
    'ы': 'ı',
    'ь': '',
    'э': 'e',
    'ю': 'yu',
    'я': 'ya'
  };
  
  const latinToCyrillicUppercase: Record<string, string> = {
    'Sh': 'Ш',
    'SH': 'Ш',
    'Ch': 'Ч',
    'CH': 'Ч',
    'Ya': 'Я',
    'YA': 'Я',
    'Yu': 'Ю',
    'YU': 'Ю',
    'A': 'А',
    'Á': 'Ә',
    'B': 'Б',
    'D': 'Д',
    'E': 'Е',
    'F': 'Ф',
    'G': 'Г',
    'Ǵ': 'Ғ',
    'H': 'Ҳ',
    'X': 'Х',
    'Í': 'Ы',
    'I': 'И',
    'J': 'Ж',
    'K': 'К',
    'Q': 'Қ',
    'L': 'Л',
    'M': 'М',
    'N': 'Н',
    'Ń': 'Ң',
    'O': 'О',
    'Ó': 'Ө',
    'P': 'П',
    'R': 'Р',
    'S': 'С',
    'T': 'Т',
    'U': 'У',
    'Ú': 'Ү',
    'V': 'В',
    'W': 'Ў',
    'Y': 'Й',
    'Z': 'З',
    'C': 'Ц'
  };
  
  const latinToCyrillicLowercase: Record<string, string> = {
    'sh': 'ш',
    'ch': 'ч',
    'ya': 'я',
    'yu': 'ю',
    'a': 'а',
    'á': 'ә',
    'b': 'б',
    'd': 'д',
    'e': 'е',
    'f': 'ф',
    'g': 'г',
    'ǵ': 'ғ',
    'h': 'ҳ',
    'x': 'х',
    'i': 'и',
    'ı': 'ы',
    'j': 'ж',
    'k': 'к',
    'q': 'қ',
    'l': 'л',
    'm': 'м',
    'n': 'н',
    'ń': 'ң',
    'o': 'о',
    'ó': 'ө',
    'p': 'п',
    'r': 'р',
    's': 'с',
    't': 'т',
    'u': 'у',
    'ú': 'ү',
    'v': 'б',
    'w': 'ў',
    'y': 'й',
    'z': 'з',
    'c': 'ц'
  };
  
  const cyrillicToLatin: Record<string, string> = { ...cyrillicToLatinUppercase, ...cyrillicToLatinLowercase };
  const latinToCyrillic: Record<string, string> = { ...latinToCyrillicUppercase, ...latinToCyrillicLowercase };
  
  export { cyrillicToLatin, latinToCyrillic };
  